'use client';

import { motion, useInView } from 'framer-motion';
import { useRef } from 'react';
import AnimatedCounter from './ui/AnimatedCounter';
import { TrendingUp, Calendar, DollarSign } from 'lucide-react';

export default function ProblemSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-100px' });

  const stats = [
    {
      icon: TrendingUp,
      value: 90,
      suffix: '%',
      label: 'of internet content will be AI-generated by 2027',
      gradient: 'from-accent-500 to-accent-300',
    },
    {
      icon: Calendar,
      value: 2028,
      suffix: '',
      label: 'Year AI runs out of human training data',
      gradient: 'from-purple-500 to-purple-400',
    },
    {
      icon: DollarSign,
      value: 0,
      suffix: '',
      label: 'What creators earn when AI copies their style',
      gradient: 'from-danger-500 to-danger-400',
    },
  ];

  return (
    <section ref={ref} className="py-32 relative overflow-hidden">
      {/* Background effects */}
      <div className="absolute inset-0 dot-pattern opacity-30" />
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-accent-500/5 rounded-full blur-3xl" />
      <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-purple-500/5 rounded-full blur-3xl" />

      <div className="container mx-auto px-6 relative z-10">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8 }}
          className="text-center max-w-4xl mx-auto mb-20"
        >
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-5xl md:text-6xl lg:text-7xl font-bold font-heading mb-8"
          >
            The Internet Has a{' '}
            <span className="gradient-text">Truth Problem</span>
          </motion.h2>
        </motion.div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto mb-20">
          {stats.map((stat, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.8, delay: 0.4 + index * 0.2 }}
              className="glass-strong p-8 rounded-3xl hover:scale-105 transition-all duration-300 group cursor-pointer relative overflow-hidden"
            >
              {/* Gradient glow on hover */}
              <div className={`absolute inset-0 bg-gradient-to-br ${stat.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-300`} />

              <div className="relative z-10">
                {/* Icon */}
                <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${stat.gradient} bg-opacity-10 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                  <stat.icon className="w-7 h-7 text-white" />
                </div>

                {/* Number */}
                <div className="text-6xl md:text-7xl font-bold font-heading mb-4 gradient-text">
                  {stat.suffix === '$' && stat.suffix}
                  <AnimatedCounter end={stat.value} duration={2.5} suffix={stat.suffix === '$' ? '' : stat.suffix} />
                </div>

                {/* Label */}
                <p className="text-white/70 text-lg leading-relaxed">
                  {stat.label}
                </p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Problem Statement */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, delay: 1 }}
          className="max-w-4xl mx-auto glass-strong p-12 md:p-16 rounded-3xl"
        >
          <div className="space-y-6 text-lg md:text-xl leading-relaxed">
            <p className="text-white/90">
              <span className="text-accent-500 font-bold">The challenge:</span>{' '}
              AI writing tools have become so sophisticated that distinguishing human from machine is nearly impossible.
            </p>
            <p className="text-white/90">
              <span className="text-purple-500 font-bold">The impact:</span>{' '}
              Misinformation spreads faster, trust erodes, and authentic voices get drowned out.
            </p>
            <p className="text-white/90">
              <span className="gradient-text font-bold">The solution:</span>{' '}
              Verifily gives you instant, accurate AI detection right in your browser—no copy-pasting, no disruption, just truth.
            </p>
          </div>
        </motion.div>

        {/* Visual Element - Abstract AI vs Human representation */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={isInView ? { opacity: 1, scale: 1 } : {}}
          transition={{ duration: 1.2, delay: 1.3 }}
          className="mt-20 max-w-3xl mx-auto"
        >
          <div className="grid grid-cols-2 gap-8">
            <div className="glass p-8 rounded-2xl text-center group hover:scale-105 transition-all">
              <div className="text-4xl mb-4">🤖</div>
              <div className="text-white/60">AI Content</div>
              <div className="text-sm text-danger-400 mt-2">Flooding the web</div>
            </div>
            <div className="glass p-8 rounded-2xl text-center group hover:scale-105 transition-all">
              <div className="text-4xl mb-4">👤</div>
              <div className="text-white/60">Human Content</div>
              <div className="text-sm text-success-400 mt-2">Needs protection</div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
