'use client';

import { motion } from 'framer-motion';

export default function ProblemSection() {
  const stats = [
    {
      value: '90%',
      label: 'of internet content will be AI-generated by 2027',
    },
    {
      value: '2028',
      label: 'Year AI runs out of human training data',
    },
    {
      value: '$0',
      label: 'What creators earn when AI copies their style',
    },
  ];

  return (
    <section style={{ background: '#0f2137' }}>
      <div className="container">
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>

          {/* Section Title */}
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            style={{ marginBottom: '80px' }}
          >
            The Internet Has a <span className="gradient-text">Truth Problem</span>
          </motion.h2>

          {/* Stats Grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: '40px',
            marginBottom: '80px'
          }}>
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="glass-strong"
                style={{
                  padding: '40px 30px',
                  borderRadius: '20px',
                  textAlign: 'center'
                }}
              >
                <div style={{
                  fontSize: '3.5rem',
                  fontWeight: 'bold',
                  marginBottom: '20px',
                  background: 'linear-gradient(135deg, #00d4ff, #8b5cf6)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text'
                }}>
                  {stat.value}
                </div>
                <p style={{
                  fontSize: '1rem',
                  lineHeight: '1.6',
                  color: 'rgba(255, 255, 255, 0.7)',
                  margin: 0
                }}>
                  {stat.label}
                </p>
              </motion.div>
            ))}
          </div>

          {/* Problem Statement */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="glass-strong"
            style={{
              padding: '50px 60px',
              borderRadius: '20px',
              maxWidth: '900px',
              margin: '0 auto',
              textAlign: 'left'
            }}
          >
            <p style={{ marginBottom: '20px' }}>
              <span style={{ color: '#00d4ff', fontWeight: 'bold' }}>The challenge:</span>{' '}
              AI writing tools have become so sophisticated that distinguishing human from machine is nearly impossible.
            </p>
            <p style={{ marginBottom: '20px' }}>
              <span style={{ color: '#8b5cf6', fontWeight: 'bold' }}>The impact:</span>{' '}
              Misinformation spreads faster, trust erodes, and authentic voices get drowned out.
            </p>
            <p style={{ margin: 0 }}>
              <span className="gradient-text" style={{ fontWeight: 'bold' }}>The solution:</span>{' '}
              Verifily gives you instant, accurate AI detection right in your browser—no copy-pasting, no disruption, just truth.
            </p>
          </motion.div>

        </div>
      </div>
    </section>
  );
}
